version: '3.3'
services:
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'carangobom'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: ''
#      MYSQL_ROOT_PASSWORD: ''
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#      MYSQL_ROOT_HOST: '%'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - my-db:/var/lib/mysql
  db:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=carangobom_application
      - APP_DB_PASS=qgwuygfuwyegfq6787326tq7236gf
      - APP_DB_NAME=carangobom
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
#  api:
#    image: caelum/clines-api
#    environment:
#      DB_HOST: db
#    ports:
#      - "8080:8080"  
volumes:
  my-db: